version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: hodlbook_server_1
      APP_PORT: 2008

  server:
    image: ghcr.io/hodlbook/hodlbook:v0.1.11
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - APP_ENV=production
      - APP_PORT=2008
      - DB_TYPE=sqlite
      - DB_PATH=/data/hodlbook.db
      - DEFAULT_CURRENCY=USD
